#pragma once

// ---- CONTROL KEYS ----
#define QUIT 'q'
#define MOVE_UP 'w'
#define MOVE_DOWN 's'
#define MOVE_LEFT 'a'
#define MOVE_RIGHT 'd'
#define INCREASE_SPEED 'p'
#define DECREASE_SPEED 'o'

#define UP_DIRECTION -1
#define DOWN_DIRECTION 1
#define LEFT_DIRECTION -1
#define RIGHT_DIRECTION 1

#define PLAYER_SPRITE_UP '^'
#define PLAYER_SPRITE_DOWN 'v'
#define PLAYER_SPRITE_LEFT '<'
#define PLAYER_SPRITE_RIGHT '>'

#define FRAMES_PER_SECOND 200
#define SPEED_FACTOR (1000/(FRAMES_PER_SECOND*100.0))

#define BORDER_SIZE 1
#define MAX_STARS 25
#define MAX_HUNTERS 15
#define HUNTER_WAIT_TIME 200
#define HUNTER_DASH_TIME 150
#define DASH_SPEED_MULTIPLIER 3

#define HUNTER_DAMAGE_HIGH 5
#define HUNTER_DAMAGE_MEDIUM 3
#define HUNTER_DAMAGE_LOW 1

#define BIRD_TYPE 'b'
#define HUNTER_TYPE 'h'
#define STAR_TYPE 's'
#define EMPTY_TYPE 'e'
#define WALL_TYPE 'w'

#define COLOR_GAME_BACKGROUND 16
#define COLOR_GAME_FOREGROUND 17
#define COLOR_STATUS_BACKGROUND 18
#define COLOR_STATUS_FOREGROUND 19
#define COLOR_STAR 20
#define COLOR_BIRD_LIFE_FORCE_FULL 21
#define COLOR_BIRD_LIFE_FORCE_HALF 22
#define COLOR_BIRD_LIFE_FORCE_LAST 23
#define COLOR_HUNTER_DAMAGE_HIGH 24
#define COLOR_HUNTER_DAMAGE_MEDIUM 25
#define COLOR_HUNTER_DAMAGE_LOW 26

#define PAIR_GAME_DEFAULT 1
#define PAIR_STATUS 2
#define PAIR_STAR 3
#define PAIR_BIRD_LIFE_FORCE_FULL 4
#define PAIR_BIRD_LIFE_FORCE_HALF 5
#define PAIR_BIRD_LIFE_FORCE_LAST 6
#define PAIR_HUNTER_DAMAGE_HIGH 7
#define PAIR_HUNTER_DAMAGE_MEDIUM 8
#define PAIR_HUNTER_DAMAGE_LOW 9
